name: CI (Dependabot branches)
on:
  pull_request_target:
    branches: [master]

env:
  MIX_ENV: test
  V3_URL: ${{ secrets.V3_URL }}
  V3_API_KEY: ${{ secrets.V3_API_KEY }}
  RECAPTCHA_PUBLIC_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
  RECAPTCHA_PRIVATE_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
  OPEN_TRIP_PLANNER_URL: ${{ secrets.OPEN_TRIP_PLANNER_URL }}

# Run unit and integration tests, no skipping, minimal caching.
jobs:
  ci:
    name: Run entire CI suite
    if: ${{ contains(github.head_ref, 'dependabot/hex') || contains(github.head_ref, 'dependabot/npm_and_yarn') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Check out the pull request HEAD
        ref: ${{ github.event.pull_request.head.sha }}
    # ASDF. Used the cached.
    - uses: asdf-vm/actions/setup@v1
    - uses: actions/cache@v2
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-asdf-cache-${{ hashFiles('.tool-versions') }}
      id: asdf-cache
    - uses: asdf-vm/actions/install@v1
      if: ${{ steps.asdf-cache.outputs.cache-hit != 'true' }}

    - name: Install Elixir dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: Install Node dependencies
      run: |
        git config --global url."https://github.com/".insteadOf ssh://git@github.com/
        npm run install:ci

    # Build assets
    - run: mix compile.assets

    - name: Build application
      run: mix compile --warnings-as-errors

    # The Tests
    - name: Unit tests / Elixir / --exclude wallaby --cover
      run: npm run ci:unit:exunit
    - name: Unit tests / JavaScript / Mocha
      run: npm run ci:unit:mocha
      if: always()
    - name: Unit tests / JavaScript & TypeScript / Jest
      run: npm run ci:unit:jest
      if: always()
    - name: Integration tests / Elixir
      run: npm run ci:integration:ex
      if: always()
    - name: Integration tests / Cypress
      run: npm run ci:integration:cypress
      if: always()
